install.packages("tidyverse", dependencies = TRUE)
install.packages("rmarkdown", dependencies = TRUE)
install.packages("IRkernel", dependencies = TRUE)
install.packages("shiny"), dependencies = TRUE)
install.packages("dplyr"), dependencies = TRUE)
install.packages("readr"), dependencies = TRUE)
install.packages("ggplot2"), dependencies = TRUE)
install.packages("lubridate"), dependencies = TRUE)

IRkernel::installspec(user = FALSE)
